# Generated by Django 3.1.7 on 2021-05-18 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('year_id', models.AutoField(primary_key=True, serialize=False)),
                ('acd_year', models.TextField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseAcademic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100)),
                ('year_id', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('hod', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyDetails',
            fields=[
                ('fid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('deptname', models.CharField(max_length=100)),
                ('phoneno', models.TextField()),
                ('email', models.TextField()),
                ('photo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FacultyDesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField()),
                ('fid', models.ForeignKey(db_column='fid', on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.facultydetails')),
            ],
        ),
    ]
