# Generated by Django 3.1.7 on 2021-05-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_auto_20210520_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('usertype', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='academicyear',
            table='academic_year',
        ),
        migrations.AlterModelTable(
            name='courseacademic',
            table='course_academic',
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='facultydesignation',
            table='faculty_designation',
        ),
        migrations.AlterModelTable(
            name='facultydetails',
            table='faculty_details',
        ),
    ]
